plugins {
    id 'com.android.application'
}

android {
    namespace "com.aexon"
    compileSdk 36
    buildToolsVersion "36.0.0"
    ndkVersion "29.0.14033849"

    defaultConfig {
        applicationId "com.aexon"
        minSdk 26
        targetSdk 36
        versionCode 1017
        versionName "1.3"
    }

    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
            applicationIdSuffix ".debug"
            debuggable true
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), rootProject.file('proguard-rules.pro')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'dev.rikka.shizuku:api:13.0.0'
    implementation 'dev.rikka.shizuku:provider:13.0.0'

    implementation 'androidx.annotation:annotation:1.3.0'
}