plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace "com.aexon"
    compileSdk 36
    buildToolsVersion "36.0.0"

    defaultConfig {
        applicationId "com.aexon"
        minSdk 26
        targetSdk 36
        versionCode 1018
        versionName "1.4"
    }

    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
            applicationIdSuffix ".debug"
            debuggable true
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), rootProject.file('proguard-rules.pro')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    implementation 'dev.rikka.shizuku:api:13.0.0'
    implementation 'dev.rikka.shizuku:provider:13.0.0'
    
    implementation 'com.google.android.material:material:1.14.0'

    implementation 'androidx.annotation:annotation:1.10.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.fragment:fragment:1.8.5'
    implementation 'androidx.activity:activity:1.9.3'
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.lifecycle:lifecycle-runtime:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.8.7'
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        freeCompilerArgs += ["-nowarn"]
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:-deprecation"
}