-repackageclasses
-flattenpackagehierarchy
-allowaccessmodification         
-ignorewarnings                  
-dontnote                        
-dontwarn
-optimizations !code/simplification/arithmetic 
-optimizationpasses 5           
-overloadaggressively